const STRINGS = {
  pl: {
    // Nav & layout
    'nav.dashboard': 'Panel',
    'nav.newOrder': 'Nowe zlecenie',
    'nav.settings': 'Ustawienia',
    'nav.logOut': 'Wyloguj się',
    'nav.orders': 'Zlecenia',
    'nav.addresses': 'Adresy',
    'nav.drivers': 'Kierowcy',
    'nav.poweredBy': 'Powered by LGK Courier',

    // Dashboard
    'dashboard.title': 'Panel',
    'dashboard.activeDeliveries': 'Aktywne dostawy',
    'dashboard.pendingOrders': 'Oczekujące zlecenia',
    'dashboard.completedToday': 'Ukończone dziś',
    'dashboard.noActive': 'Brak aktywnych dostaw',
    'dashboard.noPending': 'Brak oczekujących zleceń',
    'dashboard.noCompleted': 'Brak ukończonych dostaw dziś',
    'dashboard.loading': 'Ładowanie...',
    'dashboard.refresh': '⟳ Odśwież',
    'dashboard.updated': 'Zaktualizowano',
    'dashboard.autoRefresh': 'odświeża się co 30s',
    'dashboard.track': 'Śledź',
    'dashboard.viewProof': 'Zobacz dowód',
    'dashboard.ordersMonth': 'Zlecenia (mies.)',
    'dashboard.spentMonth': 'Wydatki (mies.)',
    'dashboard.successRate': 'Skuteczność',

    // Status labels
    'status.awaitingPayment': 'Oczekuje na płatność',
    'status.pending': 'Oczekujące',
    'status.assigned': 'Przydzielone',
    'status.collected': 'Odebrane',
    'status.inTransit': 'W drodze',
    'status.delivered': 'Dostarczone',
    'status.cancelled': 'Anulowane',

    // Orders
    'orders.title': 'Zlecenia',
    'orders.new': 'Nowe zlecenie',
    'orders.search': 'Szukaj zleceń...',
    'orders.all': 'Wszystkie',
    'orders.thisMonth': 'Ten miesiąc',
    'orders.history': 'Historia zleceń',
    'orders.noOrders': 'Brak zleceń',
    'orders.placeFirst': '+ Złóż pierwsze zlecenie',
    'orders.firstFree': 'Pierwsza dostawa gratis · Potwierdzenie GPS w cenie',
    'orders.success_title': 'Zlecenie złożone!',
    'orders.success_body': 'Kurier zostanie przydzielony w ciągu 3–8 minut.',

    // New order form
    'order.pickup': 'Nadawca',
    'order.delivery': 'Odbiorca',
    'order.package': 'Paczka',
    'order.options': 'Opcje',
    'order.priceBreakdown': 'Szczegóły ceny',
    'order.total': 'Łącznie',
    'order.place': 'Złóż zlecenie',
    'order.placing': 'Wysyłanie...',
    'order.insurance': 'Ochrona przesyłki',
    'order.insuranceNote': 'Pokrywa utratę lub uszkodzenie do 500 PLN',
    'order.fragile': 'Paczka krucha',
    'order.asap': 'Natychmiast (1-2 godz.)',
    'order.sameDay': 'Tego samego dnia (do 18:00)',
    'order.scheduled': 'Zaplanowane',
    'order.weight': 'Waga',
    'order.timeWindow': 'Czas realizacji',
    'order.whatsapp': 'Powiadomienia WhatsApp',
    'order.contactName': 'Imię i nazwisko',
    'order.contactPhone': 'Numer telefonu',
    'order.instructions': 'Instrukcje specjalne (opcjonalnie)',
    'order.accessCode': 'Kod wejścia / brama (opcjonalnie)',
    'order.cityRate': 'Stawka miejska',
    'order.distance': 'Dystans',
    'order.save': 'Zapisz',
    'order.skip': 'Pomiń',
    'order.saveAddress': 'Zapisać ten adres na później?',
    'order.saveRecipient': 'Zapisać odbiorcę na później?',
    'order.pickupPlaceholder': 'Wklej adres nadania np. ul. Mickiewicza 15/3, 70-383 Szczecin',
    'order.deliveryPlaceholder': 'Wklej adres odbiorcy np. Anna Nowak, ul. Piastów 22/4, 70-001 Szczecin',
    'order.pickupFromProfile': 'ADRES ODBIORU (Z PROFILU)',
    'order.pickupRestaurant': 'ADRES RESTAURACJI',
    'order.changePickup': 'Użyj innego adresu dla tego zamówienia',
    'order.useProfileAddress': '↑ Użyj adresu z profilu',
    'order.differentPickup': 'Inny adres odbioru',
    'order.orderOnly': 'Dotyczy tylko tego zamówienia. Nie zmienia adresu w profilu.',
    'order.noAddress': 'Brak adresu — uzupełnij w ustawieniach',
    'order.restaurantRecipient': 'Imię i nazwisko klienta',
    'order.restaurantNote': 'Kurier odbierze z restauracji i dostarczy klientowi.',
    'order.readyNow': '🟢 Teraz (0–15 min)',
    'order.ready15': '🕐 Za 15 minut (czas przygotowania)',
    'order.ready30': '🕐 Za 30 minut',
    'order.ready1hr': '🕑 Za godzinę',
    'order.readyCustom': '📅 Inna godzina',

    // Payment
    'payment.required': 'Płatność wymagana',
    'payment.desc': 'Twoje zlecenie jest zarezerwowane. Opłać je, aby przydzielić kuriera.',
    'payment.payNow': 'Zapłać teraz',
    'payment.revolut': 'Zapłać przez Revolut',
    'payment.alreadyPaid': 'Już zapłaciłem — płatność może potrwać 1-2 minuty. Ta strona odświeża się automatycznie.',

    // Settings
    'settings.title': 'Ustawienia',
    'settings.companyInfo': 'Dane firmy',
    'settings.billing': 'Płatności',
    'settings.notifications': 'Powiadomienia',
    'settings.saveChanges': 'Zapisz zmiany',
    'settings.saving': 'Zapisywanie...',
    'settings.saved': 'Zapisano ✓',
    'settings.deleteAccount': 'Usuń konto',
    'settings.dangerZone': 'Strefa niebezpieczna',
    'settings.language': 'Język',
    'settings.theme': 'Motyw',
    'settings.logo_error': 'Błąd przesyłania logo. Spróbuj ponownie.',
    'settings.delete_error': 'Usunięcie konta nie powiodło się. Spróbuj ponownie.',

    // Addresses
    'addresses.title': 'Zapisane adresy',
    'addresses.none': 'Brak zapisanych adresów. Pojawią się tutaj po pierwszym zleceniu.',
    'addresses.setDefault': 'Ustaw jako domyślny',
    'addresses.delete': 'Usuń',

    // Auth
    'auth.signIn': 'Zaloguj się',
    'auth.signUp': 'Utwórz konto',
    'auth.email': 'E-mail',
    'auth.password': 'Hasło',
    'auth.companyName': 'Nazwa firmy',
    'auth.noAccount': 'Nie masz konta?',
    'auth.haveAccount': 'Masz już konto?',
    'auth.pleaseWait': 'Proszę czekać...',
    'auth.forgotPassword': 'Nie pamiętasz hasła?',
    'auth.backToSignIn': '← Powrót do logowania',
    'auth.termsAgreement': 'Logując się, akceptujesz nasze',
    'auth.termsLink': 'Regulamin',
    'auth.privacyLink': 'Politykę prywatności',
    'auth.unauthorized': 'Sesja wygasła. Zaloguj się ponownie.',

    // Error pages
    'error.not_found_title': 'Strona nie istnieje',
    'error.not_found_body': 'Sprawdź adres URL lub wróć do panelu głównego.',
    'error.back_home': 'Wróć do panelu',
    'error.generic_title': 'Coś poszło nie tak',
    'error.generic_body': 'Odśwież stronę lub skontaktuj się z nami.',
    'error.refresh': 'Odśwież',
    'error.offline_title': 'Brak połączenia',
    'error.offline_body': 'Sprawdź swoje połączenie internetowe.',

    // Weather
    'weather.good': 'Dobre warunki dzisiaj',
    'weather.alert': 'Alert pogodowy',
    'weather.loading': 'Ładowanie pogody...',
    'weather.rain': 'Zabezpiecz kruche paczki przed wyjazdem',
    'weather.wind': 'Zabezpiecz paczki na rowerze cargo',
    'weather.cold': 'Zasięg baterii e-roweru zmniejszony — planuj krótsze trasy',
    'weather.hot': 'Weź dodatkową wodę — dbaj o nawodnienie',

    // Common
    'common.loading': 'Ładowanie...',
    'common.back': '← Wstecz',
    'common.download': 'Pobierz',
    'common.print': 'Drukuj',
  },

  en: {
    // Nav & layout
    'nav.dashboard': 'Dashboard',
    'nav.newOrder': 'New Order',
    'nav.settings': 'Settings',
    'nav.logOut': 'Log Out',
    'nav.orders': 'Orders',
    'nav.addresses': 'Addresses',
    'nav.drivers': 'Drivers',
    'nav.poweredBy': 'Powered by LGK Courier',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.activeDeliveries': 'Active Deliveries',
    'dashboard.pendingOrders': 'Pending Orders',
    'dashboard.completedToday': 'Completed Today',
    'dashboard.noActive': 'No active deliveries',
    'dashboard.noPending': 'No pending orders',
    'dashboard.noCompleted': 'No completed deliveries today',
    'dashboard.loading': 'Loading...',
    'dashboard.refresh': '⟳ Refresh',
    'dashboard.updated': 'Updated',
    'dashboard.autoRefresh': 'auto-refreshes every 30s',
    'dashboard.track': 'Track',
    'dashboard.viewProof': 'View Proof',
    'dashboard.ordersMonth': 'Orders (month)',
    'dashboard.spentMonth': 'Spent (month)',
    'dashboard.successRate': 'Success rate',

    // Status labels
    'status.awaitingPayment': 'Awaiting Payment',
    'status.pending': 'Pending',
    'status.assigned': 'Assigned',
    'status.collected': 'Collected',
    'status.inTransit': 'In Transit',
    'status.delivered': 'Delivered',
    'status.cancelled': 'Cancelled',

    // Orders
    'orders.title': 'Orders',
    'orders.new': 'New Order',
    'orders.search': 'Search orders...',
    'orders.all': 'All',
    'orders.thisMonth': 'This month',
    'orders.history': 'Order History',
    'orders.noOrders': 'No orders yet',
    'orders.placeFirst': '+ Place your first order',
    'orders.firstFree': 'First delivery free · GPS proof included',
    'orders.success_title': 'Order placed!',
    'orders.success_body': 'A courier will be assigned within 3–8 minutes.',

    // New order form
    'order.pickup': 'Pickup',
    'order.delivery': 'Delivery',
    'order.package': 'Package',
    'order.options': 'Options',
    'order.priceBreakdown': 'Price Breakdown',
    'order.total': 'Total',
    'order.place': 'Place Order',
    'order.placing': 'Placing...',
    'order.insurance': 'Package Insurance',
    'order.insuranceNote': 'Covers loss or damage up to 500 PLN',
    'order.fragile': 'Fragile package',
    'order.asap': 'ASAP (1-2 hours)',
    'order.sameDay': 'Same day (by 6pm)',
    'order.scheduled': 'Scheduled',
    'order.weight': 'Weight',
    'order.timeWindow': 'Time Window',
    'order.whatsapp': 'WhatsApp delivery updates',
    'order.contactName': 'Full name',
    'order.contactPhone': 'Contact Phone',
    'order.instructions': 'Special instructions (optional)',
    'order.accessCode': 'Gate code / access instructions (optional)',
    'order.cityRate': 'City rate',
    'order.distance': 'Distance',
    'order.save': 'Save',
    'order.skip': 'Skip',
    'order.saveAddress': 'Save this address for next time?',
    'order.saveRecipient': 'Save this recipient for next time?',
    'order.pickupPlaceholder': 'Paste pickup address e.g. ul. Mickiewicza 15/3, 70-383 Szczecin',
    'order.deliveryPlaceholder': 'Paste customer address e.g. Anna Nowak, ul. Piastów 22/4, 70-001 Szczecin',

    // Payment
    'payment.required': 'Payment required',
    'payment.desc': 'Your order is reserved. Complete payment to assign a courier.',
    'payment.payNow': 'Pay now',
    'payment.revolut': 'Pay via Revolut',
    'payment.alreadyPaid': 'Already paid? Payment confirmation can take 1-2 minutes. This page refreshes automatically.',

    // Settings
    'settings.title': 'Settings',
    'settings.companyInfo': 'Company Information',
    'settings.billing': 'Billing',
    'settings.notifications': 'Notifications',
    'settings.saveChanges': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.saved': 'Saved ✓',
    'settings.deleteAccount': 'Delete Account',
    'settings.dangerZone': 'Danger Zone',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.logo_error': 'Logo upload failed. Please try again.',
    'settings.delete_error': 'Account deletion failed. Please try again.',

    // Addresses
    'addresses.title': 'Saved Addresses',
    'addresses.none': 'No saved addresses yet. They will appear here after your first order.',
    'addresses.setDefault': 'Set default',
    'addresses.delete': 'Delete',

    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Create Account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.companyName': 'Company name',
    'auth.noAccount': 'No account?',
    'auth.haveAccount': 'Have an account?',
    'auth.pleaseWait': 'Please wait...',
    'auth.forgotPassword': 'Forgot password?',
    'auth.backToSignIn': '← Back to sign in',
    'auth.termsAgreement': 'By signing in you agree to our',
    'auth.termsLink': 'Terms',
    'auth.privacyLink': 'Privacy Policy',
    'auth.unauthorized': 'Session expired. Please sign in again.',

    // Error pages
    'error.not_found_title': 'Page not found',
    'error.not_found_body': 'Check the URL or return to your dashboard.',
    'error.back_home': 'Back to dashboard',
    'error.generic_title': 'Something went wrong',
    'error.generic_body': 'Refresh the page or contact us.',
    'error.refresh': 'Refresh',
    'error.offline_title': 'No connection',
    'error.offline_body': 'Check your internet connection.',

    // Weather
    'weather.good': 'Good conditions today',
    'weather.alert': 'Weather alert',
    'weather.loading': 'Loading weather...',
    'weather.rain': 'Waterproof fragile parcels before leaving',
    'weather.wind': 'Secure packages on cargo bike',
    'weather.cold': 'E-bike battery range reduced — plan shorter routes',
    'weather.hot': 'Carry extra water — stay hydrated',

    // Common
    'common.loading': 'Loading...',
    'common.back': '← Back',
    'common.download': 'Download',
    'common.print': 'Print',

    // Order form — restaurant / pickup mode
    'order.pickupFromProfile': 'PICKUP ADDRESS (FROM PROFILE)',
    'order.pickupRestaurant': 'RESTAURANT ADDRESS',
    'order.changePickup': 'Use a different address for this order',
    'order.useProfileAddress': '↑ Use profile address',
    'order.differentPickup': 'Different pickup address',
    'order.orderOnly': 'This order only. Does not change your profile address.',
    'order.noAddress': 'No address — add in settings',
    'order.restaurantRecipient': 'Customer name',
    'order.restaurantNote': 'Courier will collect from your restaurant and deliver to the customer.',
    'order.readyNow': '🟢 Now (0–15 min)',
    'order.ready15': '🕐 In 15 minutes (prep time)',
    'order.ready30': '🕐 In 30 minutes',
    'order.ready1hr': '🕑 In 1 hour',
    'order.readyCustom': '📅 Choose time',
  },

  uk: {
    // Nav & layout
    'nav.dashboard': 'Панель',
    'nav.newOrder': 'Нове замовлення',
    'nav.settings': 'Налаштування',
    'nav.logOut': 'Вийти',
    'nav.orders': 'Замовлення',
    'nav.addresses': 'Адреси',
    'nav.drivers': 'Водії',
    'nav.poweredBy': 'Powered by LGK Courier',

    // Dashboard
    'dashboard.title': 'Панель',
    'dashboard.activeDeliveries': 'Активні доставки',
    'dashboard.pendingOrders': 'Очікуючі замовлення',
    'dashboard.completedToday': 'Завершено сьогодні',
    'dashboard.noActive': 'Немає активних доставок',
    'dashboard.noPending': 'Немає очікуючих замовлень',
    'dashboard.noCompleted': 'Немає завершених доставок сьогодні',
    'dashboard.loading': 'Завантаження...',
    'dashboard.refresh': '⟳ Оновити',
    'dashboard.updated': 'Оновлено',
    'dashboard.autoRefresh': 'автооновлення кожні 30с',
    'dashboard.track': 'Відстежити',
    'dashboard.viewProof': 'Переглянути підтвердження',
    'dashboard.ordersMonth': 'Замовлення (міс.)',
    'dashboard.spentMonth': 'Витрачено (міс.)',
    'dashboard.successRate': 'Успішність',

    // Status labels
    'status.awaitingPayment': 'Очікує оплати',
    'status.pending': 'Очікує',
    'status.assigned': 'Призначено',
    'status.collected': 'Забрано',
    'status.inTransit': 'В дорозі',
    'status.delivered': 'Доставлено',
    'status.cancelled': 'Скасовано',

    // Orders
    'orders.title': 'Замовлення',
    'orders.new': 'Нове замовлення',
    'orders.search': 'Пошук замовлень...',
    'orders.all': 'Всі',
    'orders.thisMonth': 'Цей місяць',
    'orders.history': 'Історія замовлень',
    'orders.noOrders': 'Замовлень ще немає',
    'orders.placeFirst': '+ Розмістити перше замовлення',
    'orders.firstFree': 'Перша доставка безкоштовно · GPS-підтвердження включено',
    'orders.success_title': 'Замовлення розміщено!',
    'orders.success_body': 'Кур\'єр буде призначений протягом 3–8 хвилин.',

    // New order form
    'order.pickup': 'Забір',
    'order.delivery': 'Доставка',
    'order.package': 'Пакет',
    'order.options': 'Опції',
    'order.priceBreakdown': 'Деталі ціни',
    'order.total': 'Разом',
    'order.place': 'Розмістити замовлення',
    'order.placing': 'Розміщення...',
    'order.insurance': 'Страхування пакету',
    'order.insuranceNote': 'Покриває втрату або пошкодження до 500 PLN',
    'order.fragile': 'Крихкий пакет',
    'order.asap': 'Негайно (1-2 год.)',
    'order.sameDay': 'Того ж дня (до 18:00)',
    'order.scheduled': 'Заплановано',
    'order.weight': 'Вага',
    'order.timeWindow': 'Час виконання',
    'order.whatsapp': 'Оновлення WhatsApp',
    'order.contactName': "Ім'я та прізвище",
    'order.contactPhone': 'Контактний телефон',
    'order.instructions': 'Спеціальні інструкції (необов\'язково)',
    'order.accessCode': 'Код доступу / брама (необов\'язково)',
    'order.cityRate': 'Міська ставка',
    'order.distance': 'Відстань',
    'order.save': 'Зберегти',
    'order.skip': 'Пропустити',
    'order.saveAddress': 'Зберегти цю адресу на потім?',
    'order.saveRecipient': 'Зберегти одержувача на потім?',
    'order.pickupPlaceholder': 'Введіть адресу забору...',
    'order.deliveryPlaceholder': 'Введіть адресу одержувача...',
    'order.pickupFromProfile': 'АДРЕСА ЗАБОРУ (З ПРОФІЛЮ)',
    'order.pickupRestaurant': 'АДРЕСА РЕСТОРАНУ',
    'order.changePickup': 'Використати іншу адресу для цього замовлення',
    'order.useProfileAddress': '↑ Використати адресу профілю',
    'order.differentPickup': 'Інша адреса забору',
    'order.orderOnly': 'Лише для цього замовлення. Не змінює адресу в профілі.',
    'order.noAddress': 'Немає адреси — додайте в налаштуваннях',
    'order.restaurantRecipient': "Ім'я клієнта",
    'order.restaurantNote': "Кур'єр забере з вашого ресторану та доставить клієнту.",
    'order.readyNow': '🟢 Зараз (0–15 хв)',
    'order.ready15': '🕐 За 15 хвилин (підготовка)',
    'order.ready30': '🕐 За 30 хвилин',
    'order.ready1hr': '🕑 За годину',
    'order.readyCustom': '📅 Обрати час',

    // Payment
    'payment.required': 'Необхідна оплата',
    'payment.desc': 'Ваше замовлення зарезервовано. Здійсніть оплату.',
    'payment.payNow': 'Сплатити зараз',
    'payment.revolut': 'Сплатити через Revolut',
    'payment.alreadyPaid': 'Вже оплатили? Підтвердження може зайняти 1-2 хв.',

    // Settings
    'settings.title': 'Налаштування',
    'settings.companyInfo': 'Інформація про компанію',
    'settings.billing': 'Оплата',
    'settings.notifications': 'Сповіщення',
    'settings.saveChanges': 'Зберегти зміни',
    'settings.saving': 'Збереження...',
    'settings.saved': 'Збережено ✓',
    'settings.deleteAccount': 'Видалити акаунт',
    'settings.dangerZone': 'Небезпечна зона',
    'settings.language': 'Мова',
    'settings.theme': 'Тема',
    'settings.logo_error': 'Помилка завантаження логотипу. Спробуйте ще раз.',
    'settings.delete_error': 'Не вдалося видалити акаунт. Спробуйте ще раз.',

    // Addresses
    'addresses.title': 'Збережені адреси',
    'addresses.none': 'Немає збережених адрес.',
    'addresses.setDefault': 'Встановити за замовчуванням',
    'addresses.delete': 'Видалити',

    // Auth
    'auth.signIn': 'Увійти',
    'auth.signUp': 'Створити акаунт',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.companyName': 'Назва компанії',
    'auth.noAccount': 'Немає акаунту?',
    'auth.haveAccount': 'Є акаунт?',
    'auth.pleaseWait': 'Зачекайте...',
    'auth.forgotPassword': 'Забули пароль?',
    'auth.backToSignIn': '← Назад до входу',
    'auth.termsAgreement': 'Входячи, ви погоджуєтесь з нашими',
    'auth.termsLink': 'Умовами',
    'auth.privacyLink': 'Політикою конфіденційності',
    'auth.unauthorized': 'Сесія завершена. Увійдіть знову.',

    // Error pages
    'error.not_found_title': 'Сторінку не знайдено',
    'error.not_found_body': 'Перевірте URL або поверніться до панелі.',
    'error.back_home': 'Повернутися до панелі',
    'error.generic_title': 'Щось пішло не так',
    'error.generic_body': 'Оновіть сторінку або зверніться до нас.',
    'error.refresh': 'Оновити',
    'error.offline_title': 'Немає з\'єднання',
    'error.offline_body': 'Перевірте підключення до Інтернету.',

    // Common
    'common.loading': 'Завантаження...',
    'common.back': '← Назад',
    'common.download': 'Завантажити',
    'common.print': 'Друкувати',
  },
}

export const t = (lang, key) => {
  const dict = STRINGS[lang] || STRINGS.pl
  return dict[key] ?? STRINGS.pl[key] ?? key
}

export default STRINGS
